// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inkzblfigezbemozbyry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlua3pibGZpZ2V6YmVtb3pieXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTE0MDcsImV4cCI6MjA1ODI2NzQwN30.JTbLAUn4YrTIEMGt6gdvLn2aaL8FSRwN3obCeFAnjy8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
